using System;
using System.Collections.Generic;

// Vanilla location map: OoTRandomizer LocationList.py, checked against
// zeldaret/oot save.h, z_inventory.c and each reward actor. See FUENTES.txt.
public sealed class CollectionFlag {
 public readonly string Name; public readonly bool Skull; public readonly int Offset,Width; public readonly uint Mask;
 public CollectionFlag(string name,bool skull,int offset,int width,uint mask){Name=name;Skull=skull;Offset=offset;Width=width;Mask=mask;}
 public bool Collected(byte[] b,int s){uint v=Width==4?MemoryFile.U32(b,s+Offset):(uint)((b[s+Offset]<<8)|b[s+Offset+1]);return (v&Mask)==Mask;}
 public void Set(byte[] b,int s){for(int i=0;i<Width;i++)b[s+Offset+i]|=(byte)(Mask>>(8*(Width-1-i)));}
}
public static class Collections {
 public static readonly CollectionFlag[] All={
  new CollectionFlag("KF GS Know It All House",true,0xEA8,4,0x2U),
  new CollectionFlag("KF GS Bean Patch",true,0xEA8,4,0x1U),
  new CollectionFlag("KF GS House of Twins",true,0xEA8,4,0x4U),
  new CollectionFlag("LW GS Bean Patch Near Bridge",true,0xEA8,4,0x100U),
  new CollectionFlag("LW GS Bean Patch Near Theater",true,0xEA8,4,0x200U),
  new CollectionFlag("LW GS Above Theater",true,0xEA8,4,0x400U),
  new CollectionFlag("SFM GS",true,0xEA8,4,0x800U),
  new CollectionFlag("HF GS Cow Grotto",true,0xEA4,4,0x10000U),
  new CollectionFlag("HF GS Near Kak Grotto",true,0xEA4,4,0x20000U),
  new CollectionFlag("Market GS Guard House",true,0xEA8,4,0x80000U),
  new CollectionFlag("HC GS Tree",true,0xEA8,4,0x40000U),
  new CollectionFlag("HC GS Storms Grotto",true,0xEA8,4,0x20000U),
  new CollectionFlag("LLR GS House Window",true,0xEA4,4,0x4000000U),
  new CollectionFlag("LLR GS Tree",true,0xEA4,4,0x8000000U),
  new CollectionFlag("LLR GS Rain Shed",true,0xEA4,4,0x2000000U),
  new CollectionFlag("LLR GS Back Wall",true,0xEA4,4,0x1000000U),
  new CollectionFlag("Kak GS Tree",true,0xEAC,4,0x20U),
  new CollectionFlag("Kak GS Near Gate Guard",true,0xEAC,4,0x2U),
  new CollectionFlag("Kak GS Watchtower",true,0xEAC,4,0x4U),
  new CollectionFlag("Kak GS Skulltula House",true,0xEAC,4,0x10U),
  new CollectionFlag("Kak GS House Under Construction",true,0xEAC,4,0x8U),
  new CollectionFlag("Kak GS Above Impas House",true,0xEAC,4,0x40U),
  new CollectionFlag("Graveyard GS Bean Patch",true,0xEAC,4,0x1U),
  new CollectionFlag("Graveyard GS Wall",true,0xEAC,4,0x80U),
  new CollectionFlag("DMT GS Near Kak",true,0xEA8,4,0x4000000U),
  new CollectionFlag("DMT GS Bean Patch",true,0xEA8,4,0x2000000U),
  new CollectionFlag("DMT GS Above Dodongos Cavern",true,0xEA8,4,0x8000000U),
  new CollectionFlag("DMT GS Falling Rocks Path",true,0xEA8,4,0x10000000U),
  new CollectionFlag("GC GS Center Platform",true,0xEA8,4,0x20000000U),
  new CollectionFlag("GC GS Boulder Maze",true,0xEA8,4,0x40000000U),
  new CollectionFlag("DMC GS Crate",true,0xEA8,4,0x80000000U),
  new CollectionFlag("DMC GS Bean Patch",true,0xEA8,4,0x1000000U),
  new CollectionFlag("ZR GS Tree",true,0xEAC,4,0x200U),
  new CollectionFlag("ZR GS Ladder",true,0xEAC,4,0x100U),
  new CollectionFlag("ZR GS Near Raised Grottos",true,0xEAC,4,0x1000U),
  new CollectionFlag("ZR GS Above Bridge",true,0xEAC,4,0x800U),
  new CollectionFlag("ZD GS Frozen Waterfall",true,0xEAC,4,0x4000U),
  new CollectionFlag("ZF GS Above the Log",true,0xEAC,4,0x400U),
  new CollectionFlag("ZF GS Tree",true,0xEAC,4,0x8000U),
  new CollectionFlag("ZF GS Hidden Cave",true,0xEAC,4,0x2000U),
  new CollectionFlag("LH GS Bean Patch",true,0xEAC,4,0x10000U),
  new CollectionFlag("LH GS Lab Wall",true,0xEAC,4,0x40000U),
  new CollectionFlag("LH GS Small Island",true,0xEAC,4,0x20000U),
  new CollectionFlag("LH GS Lab Crate",true,0xEAC,4,0x80000U),
  new CollectionFlag("LH GS Tree",true,0xEAC,4,0x100000U),
  new CollectionFlag("GV GS Small Bridge",true,0xEAC,4,0x2000000U),
  new CollectionFlag("GV GS Bean Patch",true,0xEAC,4,0x1000000U),
  new CollectionFlag("GV GS Behind Tent",true,0xEAC,4,0x8000000U),
  new CollectionFlag("GV GS Pillar",true,0xEAC,4,0x4000000U),
  new CollectionFlag("GF GS Top Floor",true,0xEB0,4,0x2U),
  new CollectionFlag("GF GS Archery Range",true,0xEB0,4,0x1U),
  new CollectionFlag("Wasteland GS",true,0xEB0,4,0x200U),
  new CollectionFlag("Colossus GS Bean Patch",true,0xEB0,4,0x100U),
  new CollectionFlag("Colossus GS Tree",true,0xEB0,4,0x800U),
  new CollectionFlag("Colossus GS Hill",true,0xEB0,4,0x400U),
  new CollectionFlag("OGC GS",true,0xEA8,4,0x10000U),
  new CollectionFlag("Deku Tree GS Compass Room",true,0xE9C,4,0x8U),
  new CollectionFlag("Deku Tree GS Basement Vines",true,0xE9C,4,0x4U),
  new CollectionFlag("Deku Tree GS Basement Gate",true,0xE9C,4,0x2U),
  new CollectionFlag("Deku Tree GS Basement Back Room",true,0xE9C,4,0x1U),
  new CollectionFlag("Dodongos Cavern GS Side Room Near Lower Lizalfos",true,0xE9C,4,0x1000U),
  new CollectionFlag("Dodongos Cavern GS Scarecrow",true,0xE9C,4,0x200U),
  new CollectionFlag("Dodongos Cavern GS Alcove Above Stairs",true,0xE9C,4,0x400U),
  new CollectionFlag("Dodongos Cavern GS Vines Above Stairs",true,0xE9C,4,0x100U),
  new CollectionFlag("Dodongos Cavern GS Back Room",true,0xE9C,4,0x800U),
  new CollectionFlag("Jabu Jabus Belly GS Water Switch Room",true,0xE9C,4,0x80000U),
  new CollectionFlag("Jabu Jabus Belly GS Lobby Basement Lower",true,0xE9C,4,0x10000U),
  new CollectionFlag("Jabu Jabus Belly GS Lobby Basement Upper",true,0xE9C,4,0x20000U),
  new CollectionFlag("Jabu Jabus Belly GS Near Boss",true,0xE9C,4,0x40000U),
  new CollectionFlag("Bottom of the Well GS West Inner Room",true,0xEA4,4,0x4U),
  new CollectionFlag("Bottom of the Well GS East Inner Room",true,0xEA4,4,0x2U),
  new CollectionFlag("Bottom of the Well GS Like Like Cage",true,0xEA4,4,0x1U),
  new CollectionFlag("Forest Temple GS First Room",true,0xE9C,4,0x2000000U),
  new CollectionFlag("Forest Temple GS Lobby",true,0xE9C,4,0x8000000U),
  new CollectionFlag("Forest Temple GS Raised Island Courtyard",true,0xE9C,4,0x1000000U),
  new CollectionFlag("Forest Temple GS Level Island Courtyard",true,0xE9C,4,0x4000000U),
  new CollectionFlag("Forest Temple GS Basement",true,0xE9C,4,0x10000000U),
  new CollectionFlag("Fire Temple GS Boss Key Loop",true,0xEA0,4,0x2U),
  new CollectionFlag("Fire Temple GS Song of Time Room",true,0xEA0,4,0x1U),
  new CollectionFlag("Fire Temple GS Boulder Maze",true,0xEA0,4,0x4U),
  new CollectionFlag("Fire Temple GS Scarecrow Climb",true,0xEA0,4,0x10U),
  new CollectionFlag("Fire Temple GS Scarecrow Top",true,0xEA0,4,0x8U),
  new CollectionFlag("Water Temple GS Behind Gate",true,0xEA0,4,0x100U),
  new CollectionFlag("Water Temple GS Near Boss Key Chest",true,0xEA0,4,0x800U),
  new CollectionFlag("Water Temple GS Central Pillar",true,0xEA0,4,0x400U),
  new CollectionFlag("Water Temple GS Falling Platform Room",true,0xEA0,4,0x200U),
  new CollectionFlag("Water Temple GS River",true,0xEA0,4,0x1000U),
  new CollectionFlag("Shadow Temple GS Invisible Blades Room",true,0xEA0,4,0x8000000U),
  new CollectionFlag("Shadow Temple GS Falling Spikes Room",true,0xEA0,4,0x2000000U),
  new CollectionFlag("Shadow Temple GS Single Giant Pot",true,0xEA0,4,0x1000000U),
  new CollectionFlag("Shadow Temple GS Near Ship",true,0xEA0,4,0x10000000U),
  new CollectionFlag("Shadow Temple GS Triple Giant Pot",true,0xEA0,4,0x4000000U),
  new CollectionFlag("Spirit Temple GS Metal Fence",true,0xEA0,4,0x100000U),
  new CollectionFlag("Spirit Temple GS Sun on Floor Room",true,0xEA0,4,0x80000U),
  new CollectionFlag("Spirit Temple GS Hall After Sun Block Room",true,0xEA0,4,0x10000U),
  new CollectionFlag("Spirit Temple GS Lobby",true,0xEA0,4,0x40000U),
  new CollectionFlag("Spirit Temple GS Boulder Room",true,0xEA0,4,0x20000U),
  new CollectionFlag("Ice Cavern GS Spinning Scythe Room",true,0xEA4,4,0x200U),
  new CollectionFlag("Ice Cavern GS Heart Piece Room",true,0xEA4,4,0x400U),
  new CollectionFlag("Ice Cavern GS Push Block Room",true,0xEA4,4,0x100U),
  new CollectionFlag("LW Ocarina Memory Game",false,0xEF2,2,0x80U),
  new CollectionFlag("LW Skull Kid",false,0xEF2,2,0x40U),
  new CollectionFlag("HF Tektite Grotto Freestanding PoH",false,0x7A8,4,0x2U),
  new CollectionFlag("HF Deku Scrub Grotto",false,0xEF0,2,0x800U),
  new CollectionFlag("Market Bombchu Bowling Second Prize",false,0xEF2,2,0x4U),
  new CollectionFlag("Market Lost Dog",false,0xF2A,2,0x2U),
  new CollectionFlag("Market Treasure Chest Game Reward",false,0xEF2,2,0x800U),
  new CollectionFlag("LLR Freestanding PoH",false,0x930,4,0x2U),
  new CollectionFlag("Kak Impas House Freestanding PoH",false,0x6E4,4,0x2U),
  new CollectionFlag("Kak Windmill Freestanding PoH",false,0x8C0,4,0x2U),
  new CollectionFlag("Kak Man on Roof",false,0xEF2,2,0x20U),
  new CollectionFlag("Kak 50 Gold Skulltula Reward",false,0xEEE,2,0x4000U),
  new CollectionFlag("Graveyard Heart Piece Grave Chest",false,0x7B8,4,0x1U),
  new CollectionFlag("Graveyard Freestanding PoH",false,0x9F4,4,0x10U),
  new CollectionFlag("Graveyard Dampe Gravedigging Tour",false,0xEF2,2,0x1000U),
  new CollectionFlag("Graveyard Dampe Race Freestanding PoH",false,0x8C0,4,0x80U),
  new CollectionFlag("DMT Freestanding PoH",false,0xB60,4,0x40000000U),
  new CollectionFlag("GC Pot Freestanding PoH",false,0xB98,4,0x80000000U),
  new CollectionFlag("DMC Volcano Freestanding PoH",false,0xB7C,4,0x100U),
  new CollectionFlag("DMC Wall Freestanding PoH",false,0xB7C,4,0x4U),
  new CollectionFlag("ZR Frogs in the Rain",false,0xEEE,2,0x40U),
  new CollectionFlag("ZR Frogs Ocarina Game",false,0xEEE,2,0x1U),
  new CollectionFlag("ZR Near Open Grotto Freestanding PoH",false,0xA10,4,0x10U),
  new CollectionFlag("ZR Near Domain Freestanding PoH",false,0xA10,4,0x800U),
  new CollectionFlag("ZD Chest",false,0xA74,4,0x1U),
  new CollectionFlag("ZF Iceberg Freestanding PoH",false,0xA9C,4,0x2U),
  new CollectionFlag("ZF Bottom Freestanding PoH",false,0xA9C,4,0x100000U),
  new CollectionFlag("LH Child Fishing",false,0xEC0,4,0x400U),
  new CollectionFlag("LH Lab Dive",false,0xEF2,2,0x1U),
  new CollectionFlag("LH Freestanding PoH",false,0xA64,4,0x40000000U),
  new CollectionFlag("GV Crate Freestanding PoH",false,0xAB8,4,0x4U),
  new CollectionFlag("GV Waterfall Freestanding PoH",false,0xAB8,4,0x2U),
  new CollectionFlag("GF Chest",false,0xB00,4,0x1U),
  new CollectionFlag("GF HBA 1000 Points",false,0xF2A,2,0x1U),
  new CollectionFlag("Colossus Freestanding PoH",false,0xAF0,4,0x2000U),
  new CollectionFlag("Ice Cavern Freestanding PoH",false,0x1DC,4,0x2U),
 };
 public static int Count(byte[] b,int s,bool skull){int n=0;foreach(var f in All)if(f.Skull==skull&&f.Collected(b,s))n++;return n;}
 public static void Apply(byte[] b,int s,EditOptions o){
  foreach(var f in All)if(f.Skull?o.AllSkulltulas:o.AllHeartPieces)f.Set(b,s);
  if(o.AllSkulltulas){b[s+0xd0]=0;b[s+0xd1]=100;MemoryFile.W32(b,s+0xa4,MemoryFile.U32(b,s+0xa4)|(1U<<23));}
  // Round 2 awards the heart piece; round 3 awards repeat rupees.
  if(o.AllHeartPieces){if(b[s+0x3f]>3)throw new Exception("Ronda de ocarina no reconocida; no se guardó.");b[s+0x3f]=3;}
 }
 public static void Verify(byte[] b,int s,EditOptions o){
  if(o.AllSkulltulas&&(Count(b,s,true)!=100||b[s+0xd0]!=0||b[s+0xd1]!=100))throw new Exception("No se pudieron verificar las 100 Skulltulas.");
  if(o.AllHeartPieces&&(Count(b,s,false)!=36||b[s+0x3f]!=3))throw new Exception("No se pudieron verificar las 36 piezas de corazón.");
 }
 public static void Describe(MemoryFile m,EditOptions o,List<string> lines){
  if(o.AllSkulltulas)lines.Add("Skulltulas recogidas: "+m.CollectedCount(true)+"/100 → 100/100; contador → 100.");
  if(o.AllHeartPieces)lines.Add("Piezas recogidas: "+m.CollectedCount(false)+"/36 → 36/36. Incluye premios y ronda de ocarina. Los corazones máximos se conservan.");
 }
}
