using System;
public static class ItemLocations { public static readonly CollectionFlag[] All={
new CollectionFlag("Graveyard Dampe Race Hookshot Chest",false,0x8B4,4,0x1U),
new CollectionFlag("Deku Tree Slingshot Chest",false,0xD4,4,0x2U),
new CollectionFlag("Dodongos Cavern Bomb Bag Chest",false,0xF0,4,0x10U),
new CollectionFlag("Jabu Jabus Belly Boomerang Chest",false,0x10C,4,0x2U),
new CollectionFlag("Bottom of the Well Lens of Truth Chest",false,0x1B4,4,0x8U),
new CollectionFlag("Forest Temple Bow Chest",false,0x128,4,0x1000U),
new CollectionFlag("Fire Temple Megaton Hammer Chest",false,0x144,4,0x20U),
new CollectionFlag("Water Temple Longshot Chest",false,0x160,4,0x80U),
new CollectionFlag("Gerudo Training Ground Maze Path Final Chest",false,0x208,4,0x1000U),
};
public static readonly CollectionFlag[] Equipment={
new CollectionFlag("KF Kokiri Sword Chest",false,0xA20,4,0x1U),
new CollectionFlag("Shadow Temple Hover Boots Chest",false,0x198,4,0x80U),
new CollectionFlag("Spirit Temple Mirror Shield Chest",false,0xAE4,4,0x200U),
new CollectionFlag("Ice Cavern Iron Boots Chest",false,0x1D0,4,0x4U),
};
public static readonly CollectionFlag[] Upgrades={
new CollectionFlag("Spirit Temple Silver Gauntlets Chest",false,0xAE4,4,0x800U),
new CollectionFlag("Ganons Castle Shadow Trial Golden Gauntlets Chest",false,0x240,4,0x20U),
};
public static readonly CollectionFlag[] Dungeons={
new CollectionFlag("Hideout 1 Torch Jail Gerudo Key",false,0x230,4,0x1000U),
new CollectionFlag("Hideout 2 Torches Jail Gerudo Key",false,0x230,4,0x8000U),
new CollectionFlag("Hideout 3 Torches Jail Gerudo Key",false,0x230,4,0x400U),
new CollectionFlag("Hideout 4 Torches Jail Gerudo Key",false,0x230,4,0x4000U),
new CollectionFlag("Deku Tree Map Chest",false,0xD4,4,0x8U),
new CollectionFlag("Deku Tree Compass Chest",false,0xD4,4,0x4U),
new CollectionFlag("Dodongos Cavern Map Chest",false,0xF0,4,0x100U),
new CollectionFlag("Dodongos Cavern Compass Chest",false,0xF0,4,0x20U),
new CollectionFlag("Jabu Jabus Belly Map Chest",false,0x10C,4,0x4U),
new CollectionFlag("Jabu Jabus Belly Compass Chest",false,0x10C,4,0x10U),
new CollectionFlag("Bottom of the Well Front Left Fake Wall Chest",false,0x1B4,4,0x100U),
new CollectionFlag("Bottom of the Well Freestanding Key",false,0x1C0,4,0x2U),
new CollectionFlag("Bottom of the Well Compass Chest",false,0x1B4,4,0x2U),
new CollectionFlag("Bottom of the Well Right Bottom Fake Wall Chest",false,0x1B4,4,0x20U),
new CollectionFlag("Bottom of the Well Map Chest",false,0x1B4,4,0x80U),
new CollectionFlag("Forest Temple First Room Chest",false,0x128,4,0x8U),
new CollectionFlag("Forest Temple First Stalfos Chest",false,0x128,4,0x1U),
new CollectionFlag("Forest Temple Map Chest",false,0x128,4,0x2U),
new CollectionFlag("Forest Temple Well Chest",false,0x128,4,0x200U),
new CollectionFlag("Forest Temple Boss Key Chest",false,0x128,4,0x4000U),
new CollectionFlag("Forest Temple Floormaster Chest",false,0x128,4,0x4U),
new CollectionFlag("Forest Temple Red Poe Chest",false,0x128,4,0x2000U),
new CollectionFlag("Forest Temple Blue Poe Chest",false,0x128,4,0x8000U),
new CollectionFlag("Fire Temple Near Boss Chest",false,0x144,4,0x2U),
new CollectionFlag("Fire Temple Boss Key Chest",false,0x144,4,0x1000U),
new CollectionFlag("Fire Temple Big Lava Room Lower Open Door Chest",false,0x144,4,0x10U),
new CollectionFlag("Fire Temple Big Lava Room Blocked Door Chest",false,0x144,4,0x4U),
new CollectionFlag("Fire Temple Boulder Maze Lower Chest",false,0x144,4,0x8U),
new CollectionFlag("Fire Temple Boulder Maze Side Room Chest",false,0x144,4,0x100U),
new CollectionFlag("Fire Temple Map Chest",false,0x144,4,0x400U),
new CollectionFlag("Fire Temple Boulder Maze Shortcut Chest",false,0x144,4,0x800U),
new CollectionFlag("Fire Temple Boulder Maze Upper Chest",false,0x144,4,0x40U),
new CollectionFlag("Fire Temple Compass Chest",false,0x144,4,0x80U),
new CollectionFlag("Fire Temple Highest Goron Chest",false,0x144,4,0x200U),
new CollectionFlag("Water Temple Compass Chest",false,0x160,4,0x200U),
new CollectionFlag("Water Temple Map Chest",false,0x160,4,0x4U),
new CollectionFlag("Water Temple Cracked Wall Chest",false,0x160,4,0x1U),
new CollectionFlag("Water Temple Torches Chest",false,0x160,4,0x2U),
new CollectionFlag("Water Temple Boss Key Chest",false,0x160,4,0x20U),
new CollectionFlag("Water Temple Central Pillar Chest",false,0x160,4,0x40U),
new CollectionFlag("Water Temple Central Bow Target Chest",false,0x160,4,0x100U),
new CollectionFlag("Water Temple River Chest",false,0x160,4,0x8U),
new CollectionFlag("Water Temple Dragon Chest",false,0x160,4,0x400U),
new CollectionFlag("Shadow Temple Map Chest",false,0x198,4,0x2U),
new CollectionFlag("Shadow Temple Compass Chest",false,0x198,4,0x8U),
new CollectionFlag("Shadow Temple Early Silver Rupee Chest",false,0x198,4,0x4U),
new CollectionFlag("Shadow Temple Falling Spikes Switch Chest",false,0x198,4,0x10U),
new CollectionFlag("Shadow Temple Freestanding Key",false,0x1A4,4,0x2U),
new CollectionFlag("Shadow Temple After Wind Hidden Chest",false,0x198,4,0x100000U),
new CollectionFlag("Shadow Temple Boss Key Chest",false,0x198,4,0x800U),
new CollectionFlag("Shadow Temple Invisible Floormaster Chest",false,0x198,4,0x2000U),
new CollectionFlag("Spirit Temple Child Early Torches Chest",false,0x17C,4,0x1U),
new CollectionFlag("Spirit Temple Map Chest",false,0x17C,4,0x8U),
new CollectionFlag("Spirit Temple Sun Block Room Chest",false,0x17C,4,0x2U),
new CollectionFlag("Spirit Temple Compass Chest",false,0x17C,4,0x10U),
new CollectionFlag("Spirit Temple Early Adult Right Chest",false,0x17C,4,0x80U),
new CollectionFlag("Spirit Temple Statue Room Hand Chest",false,0x17C,4,0x4U),
new CollectionFlag("Spirit Temple Near Four Armos Chest",false,0x17C,4,0x20U),
new CollectionFlag("Spirit Temple Boss Key Chest",false,0x17C,4,0x400U),
new CollectionFlag("Ice Cavern Map Chest",false,0x1D0,4,0x1U),
new CollectionFlag("Ice Cavern Compass Chest",false,0x1D0,4,0x2U),
new CollectionFlag("Gerudo Training Ground Stalfos Chest",false,0x208,4,0x1U),
new CollectionFlag("Gerudo Training Ground Heavy Block Third Chest",false,0x208,4,0x100000U),
new CollectionFlag("Gerudo Training Ground Eye Statue Chest",false,0x208,4,0x8U),
new CollectionFlag("Gerudo Training Ground Near Scarecrow Chest",false,0x208,4,0x10U),
new CollectionFlag("Gerudo Training Ground Hammer Room Switch Chest",false,0x208,4,0x10000U),
new CollectionFlag("Gerudo Training Ground Freestanding Key",false,0x214,4,0x2U),
new CollectionFlag("Gerudo Training Ground Underwater Silver Rupee Chest",false,0x208,4,0x2000U),
new CollectionFlag("Gerudo Training Ground Beamos Chest",false,0x208,4,0x2U),
new CollectionFlag("Gerudo Training Ground Hidden Ceiling Chest",false,0x208,4,0x800U),
new CollectionFlag("Ganons Castle Light Trial Invisible Enemies Chest",false,0x240,4,0x10000U),
new CollectionFlag("Ganons Castle Light Trial Lullaby Chest",false,0x240,4,0x20000U),
new CollectionFlag("Ganons Tower Boss Key Chest",false,0x1EC,4,0x800U),
};
}
